apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-mern-ecommerce
  namespace: argocd
  
spec:
  # The list generator lets you enumerate a static set of elements (apps).
  generators:
    - list:
        elements:
          - app: mern-ecommerce
            path: mern-helm   # path in repo for this app
            targetNamespace: mern-ecommerce
          
          
  # Template that will be used to generate individual Application CRs
  template:
    metadata:
      # name template uses the element key 'app'
      name: '{{app}}-app'
      annotations:
        # The email notifier must be configured in argocd-notifications-cm.yaml, The `.email` is the name of the notifier, i.e, `service.email` in the argocd-notifications-cm.yaml.
        # Subscribe to notifications when the app health is degraded.
        notifications.argoproj.io/subscribe.on-health-degraded.email: "cosmicshogun69@gmail.com"  # you can add multiple email ids separated by comma like "<receiver@example.com>, <receiver2@example.com>"
        # Subscribe to notifications when the app is successfully deployed.
        notifications.argoproj.io/subscribe.on-deployed.email: "cosmicshogun69@gmail.com" # you can add multiple email ids separated by comma like "<receiver@example.com>, <receiver2@example.com>"

    spec:
      project: default
      source:
        repoURL: https://github.com/Parth2496Singh/MERN-E-Commerce-Website-K8s-Gitops.git
        targetRevision: main
        path: '{{path}}'                # resolved from element
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{targetNamespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      ignoreDifferences:
          - group: apps
            kind: Deployment
            jsonPointers:
              - /spec/replicas    