apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mongodb.name }}
  namespace: {{ .Values.namespace }}

spec:
  serviceName: {{ .Values.mongodb.serviceName }}
  replicas: {{ .Values.mongodb.replicas }}

  selector:
    matchLabels:
      app: {{ .Values.mongodb.label }}

  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.label }}

    spec:
      containers:
        - name: {{ .Values.mongodb.containerName }}
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"

          ports:
            - containerPort: {{ .Values.mongodb.port }}

          volumeMounts:
            - name: {{ .Values.mongodb.volume.name }}
              mountPath: {{ .Values.mongodb.volume.mountPath }}

          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongodb.auth.username }}

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.auth.secretName }}
                  key: {{ .Values.mongodb.auth.secretKey }}

  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.mongodb.volume.name }}
      spec:
        accessModes:
          - {{ .Values.mongodb.volume.accessMode }}
        resources:
          requests:
            storage: {{ .Values.mongodb.volume.size }}