apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace }}

type: Opaque

data:
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.secrets.mongoPassword | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}